2025-05-19 13:54:16,155 interface [ERROR] An error occurred: 'MainWindow' object has no attribute 'qt_handler'
2025-05-19 13:54:16,155 interface [ERROR] Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 141, in cli
    self.gui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 182, in gui
    window = MainWindow(self.acq_ctrl, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 94, in __init__
    self.qt_handler.logMessage.connect(self.console.write) # connect the log handler to the console
    ^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'qt_handler'

2025-05-19 13:54:55,538 interface [ERROR] An error occurred: 'Interface' object has no attribute 'qt_handler'
2025-05-19 13:54:55,553 interface [ERROR] Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 141, in cli
    self.gui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 182, in gui
    window = MainWindow(self.acq_ctrl, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 94, in __init__
    self.interface.qt_handler.logMessage.connect(self.console.write) # connect the log handler to the console
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Interface' object has no attribute 'qt_handler'

2025-05-19 13:57:03,761 interface [ERROR] An error occurred: name 'logger' is not defined
2025-05-19 13:57:03,776 interface [ERROR] Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 141, in cli
    self.gui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 182, in gui
    window = MainWindow(self.acq_ctrl, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 96, in __init__
    print(logger)
          ^^^^^^
NameError: name 'logger' is not defined

2025-05-19 14:44:25,105 interface [ERROR] An error occurred: wrapped C/C++ object of type QtLogHandler has been deleted
2025-05-19 14:44:25,109 interface [ERROR] Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 153, in cli
    self.gui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 194, in gui
    window = MainWindow(self.acq_ctrl, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 95, in __init__
    self.interface.logger.qt_handler.logMessage.connect(self.console.write) # connect the log handler to the console
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type QtLogHandler has been deleted

2025-05-19 14:50:25,410 interface [ERROR] An error occurred: 'Logger' object has no attribute 'setFormatter'
2025-05-19 14:50:25,412 interface [ERROR] Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 153, in cli
    self.gui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 194, in gui
    window = MainWindow(self.acq_ctrl, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 105, in __init__
    self.logger.setFormatter(logging.Formatter('%(message)s'))
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\logging_utils.py", line 94, in __getattr__
    return getattr(self.logger, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'setFormatter'

2025-05-19 14:51:41,931 interface [ERROR] An error occurred: 'MainWindow' object has no attribute 'qt_landler'
2025-05-19 14:51:41,931 interface [ERROR] Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 153, in cli
    self.gui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 194, in gui
    window = MainWindow(self.acq_ctrl, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 100, in __init__
    self.qt_landler.setFormatter(logging.Formatter('%(message)s'))
    ^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'qt_landler'

2025-05-19 14:51:59,799 interface.MainWindow [ERROR] Error disconnecting log handler: 'Logger' object has no attribute 'qt_handler'
2025-05-19 14:52:50,452 interface.MainWindow [ERROR] Error disconnecting log handler: 'Logger' object has no attribute 'qt_handler'
2025-05-19 15:19:45,803 interface [ERROR] An error occurred: QtLogHandler.__init__() got an unexpected keyword argument 'parent'
2025-05-19 15:19:45,803 interface [ERROR] Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 153, in cli
    self.gui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 194, in gui
    window = MainWindow(self.acq_ctrl, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 100, in __init__
    self.qt_handler = QtLogHandler(parent=self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: QtLogHandler.__init__() got an unexpected keyword argument 'parent'

2025-05-19 16:28:32,915 interface.camera_scanner [ERROR] Unexpected error during scan: 'function' object has no attribute 'is_set'
2025-05-19 16:30:02,980 interface.camera_scanner [ERROR] Unexpected error during scan: Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\acqcontrol.py", line 171, in _acquire_scan
    if cancel_event.is_set():
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'is_set'

2025-05-19 16:32:26,246 interface.camera_scanner [ERROR] Unexpected error during scan: Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\acqcontrol.py", line 179, in _acquire_scan
    success, image_data = self._execute_step(step, timeout)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\acqcontrol.py", line 218, in _execute_step
    for command, change in zip(self.acq_ctrl.command_hierarchy, step):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AcquisitionControl' object has no attribute 'command_hierarchy'

2025-05-19 16:33:17,864 interface.camera_scanner [ERROR] Unexpected error during scan: Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\acqcontrol.py", line 179, in _acquire_scan
    success, image_data = self._execute_step(step, timeout)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\acqcontrol.py", line 218, in _execute_step
    for command, change in zip(self.acq_ctrl.scan_command_hierarchy, step):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AcquisitionControl' object has no attribute 'scan_command_hierarchy'

2025-05-19 16:33:49,405 interface.camera_scanner [ERROR] Unexpected error during scan: Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\acqcontrol.py", line 187, in _acquire_scan
    wavelength_axis=self.wavelength_axis,
                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CameraScanner' object has no attribute 'wavelength_axis'

2025-05-19 20:50:10,799 interface [ERROR] An error occurred: 'MainWindow' object has no attribute 'scan_complete_signal'
2025-05-19 20:50:10,799 interface [ERROR] Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 153, in cli
    self.gui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 194, in gui
    window = MainWindow(self.acq_ctrl, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 115, in __init__
    self.scan_complete_signal.connect(self.scan_finished)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'scan_complete_signal'

2025-05-19 20:51:57,686 interface [ERROR] An error occurred: 'MainWindow' object has no attribute 'update_progress_bar'
2025-05-19 20:51:57,688 interface [ERROR] Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 153, in cli
    self.gui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 194, in gui
    window = MainWindow(self.acq_ctrl, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 119, in __init__
    self.progress_update_signal.connect(self.update_progress_bar)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'update_progress_bar'

2025-05-19 21:18:19,167 interface [ERROR] An error occurred: unsupported format string passed to dict.__format__
2025-05-19 21:18:19,169 interface [ERROR] Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 154, in cli
    self.gui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 195, in gui
    window = MainWindow(self.acq_ctrl, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 123, in __init__
    self.refresh_ui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 413, in refresh_ui
    self.lbl_spectrometer.setText(f"{self.interface.microscope.report_spectrometer_wavelength:.2f} nm")
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported format string passed to dict.__format__

2025-05-19 21:20:48,066 interface [ERROR] An error occurred: type dict doesn't define __round__ method
2025-05-19 21:20:48,066 interface [ERROR] Traceback (most recent call last):
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 154, in cli
    self.gui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\interface_run_me.py", line 195, in gui
    window = MainWindow(self.acq_ctrl, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 123, in __init__
    self.refresh_ui()
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\acquisitioncontrol\pyqtGUI.py", line 413, in refresh_ui
    self.lbl_spectrometer.setText(f"{self.interface.microscope.report_spectrometer_wavelength:.2f} nm")
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sam\matchbook\ramanproject\RamanMicroscope\instruments_old.py", line 1497, in report_spectrometer_wavelength
    return round(self.spectrometer_wavelength, 2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type dict doesn't define __round__ method

